################################
## Airflow Metadata Secret
#################################
{{- $host := .Values.data.metadataConnection.host }}
{{- $port := ((.Values.data.metadataConnection.port) | toString) }}
{{- $database := (.Values.data.metadataConnection.db) }}
{{- $query := ternary (printf "sslmode=%s" .Values.data.metadataConnection.sslmode) "" (eq .Values.data.metadataConnection.protocol "postgresql") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-metadata
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- with .Values.data.metadataConnection }}
  connection: {{ urlJoin (dict "scheme" .protocol "userinfo" (printf "%s:%s" (.user | urlquery) (.pass | urlquery) ) "host" (printf "%s:%s" $host $port) "path" (printf "/%s" $database) "query" $query) | b64enc | quote }}
  {{- end }}