############################################
## Airflow Webserver Flask Secret Key Secret
############################################
{{ $generated_secret_key := (randAlphaNum 32 | b64enc) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webserver-secret-key
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  webserver-secret-key: {{ $generated_secret_key | b64enc | quote }}