################################
## Airflow Run Migrations
#################################
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-run-airflow-migrations
  labels:
    tier: airflow
    component: run-airflow-migrations
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  {{- $annotations := dict }}
  {{- if .Values.migrateDatabaseJob.useHelmHooks }}
    {{- $_ := set $annotations "helm.sh/hook" "post-install,post-upgrade" }}
    {{- $_ := set $annotations "helm.sh/hook-weight" "1" }}
    {{- $_ := set $annotations "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded" }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        tier: airflow
        component: run-airflow-migrations
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: run-airflow-migrations
          image: {{ template "airflow_image_for_migrations" . }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          {{- if .Values.migrateDatabaseJob.command }}
          command: {{- tpl (toYaml .Values.migrateDatabaseJob.command) . | nindent 12 }}
          {{- end }}
          {{- if .Values.migrateDatabaseJob.args }}
          args: {{- tpl (toYaml .Values.migrateDatabaseJob.args) . | nindent 12 }}
          {{- end }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          {{- include "standard_airflow_environment" . | indent 10 }}
          volumeMounts:
            {{- include "airflow_config_mount" . | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "airflow_config" . }}