################################
## Airflow Redis Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    tier: airflow
    component: redis
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: redis
    release: {{ .Release.Name }}
  ports:
    - name: redis-db
      protocol: TCP
      port: {{ .Values.ports.redisDB }}
      targetPort: {{ .Values.ports.redisDB }}
